version: '3.8'

services:
  # User Service
  user-service:
    build:
      context: ./backend
      dockerfile: /user-service/Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      - DB_URI=mongodb://mongodb:27017/user-db
    networks:
      - backend

  # Project Service
  project-service:
    build:
      context: ./backend/project-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
    environment:
      - DB_URI=mongodb://mongodb:27017/project-db
    networks:
      - backend

  # Task Service
  task-service:
    build:
      context: ./backend/task-service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    depends_on:
      - mongodb
    environment:
      - DB_URI=mongodb://mongodb:27017/task-db
    networks:
      - backend

  # Notification Service
  notification-service:
    build:
      context: ./backend/notification-service
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    depends_on:
      - mongodb
    environment:
      - DB_URI=mongodb://mongodb:27017/notification-db
    networks:
      - backend

  # Milestone Service
  milestone-service:
    build:
      context: ./backend/milestone-service
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    depends_on:
      - mongodb
    environment:
      - DB_URI=mongodb://mongodb:27017/milestone-db
    networks:
      - backend

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - project-service
      - task-service
      - notification-service
      - milestone-service

  # MongoDB Service for all backend services
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongo_data:
