version: '3.8'

services:
  user-service:
    build: ./backend/user-service
    ports:
      - "3001:3001"
    environment:
      - DB_URI=mongodb://mongo:27017/users
    depends_on:
      - mongo

  project-service:
    build: ./backend/project-service
    ports:
      - "3002:3002"
    environment:
      - DB_URI=mysql://mysql:3306/projects
    depends_on:
      - mysql

  task-service:
    build: ./backend/task-service
    ports:
      - "3003:3003"
    environment:
      - DB_URI=mongodb://mongo:27017/tasks
    depends_on:
      - mongo

  notification-service:
    build: ./backend/notification-service
    ports:
      - "3004:3004"
    environment:
      - DB_URI=mongodb://mongo:27017/notifications
    depends_on:
      - mongo

  milestone-service:
    build: ./backend/milestone-service
    ports:
      - "3005:3005"
    environment:
        - DB_URI=mongodb://mongo:27017/milestones
    depends_on:
        - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongo-data:
  mysql-data:
