name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push user Image
        uses: docker/build-push-action@v5
        with:
          context: ./user-service
          file: ./backend/user-service/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/forkina-user-service:latest

      - name: Build and push milestone Image
        uses: docker/build-push-action@v5
        with:
          context: ./milestone-service
          file: ./backend/milestone-service/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/forkina-milestone-service:latest

      - name: Build and push notification Image
        uses: docker/build-push-action@v5
        with:
          context: ./notification-service
          file: ./backend/notification-service/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/forkina-notification-service:latest

      - name: Build and push project Image
        uses: docker/build-push-action@v5
        with:
          context: ./project-service
          file: ./backend/project-service/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/forkina-project-service:latest

      - name: Build and push task Image
        uses: docker/build-push-action@v5
        with:
          context: ./task-service
          file: ./backend/task-service/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/forkina-task-service:latest

      - name: Build and push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/forkina-frontend:latest.
